# Generated by Django 2.2.3 on 2019-07-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
